### ISSUE TITLE
Wow! Not a single bit of work yet

### ISSUE THREAD

**Issue by jewpaltz** [MadhuRakshith15/ExerciseApp#1]
Unless you start working. You will fail this class.
I was shocked to see that you've done absolutely nothing

**Comment by MadhuRakshith15** [comment]
Hi Professor,
Sorry for the miss communication from my side.
The way I thought about how it works is like, once we complete one feature we need to push the code into the repo, so as of now I was just going with Javascript, jquery, and vue practice session. 
I didn't really push anything into the repo. From now on whatever I practice or If I update the features, You can see the changes in my repo.
